# Generated by Django 4.0.4 on 2022-05-15 00:43

import ckeditor.fields
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('tipo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('detalles', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('identidad', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('raza', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], max_length=255)),
                ('esterilizado', models.BooleanField(default=False)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('apellido', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo se admiten letras')])),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('veterinario', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.ficha')),
            ],
        ),
    ]
