# Generated by Django 4.0.4 on 2022-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='qr',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
